name: Testing
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "********Step 1*******"
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "********Step 2*******"
          git fetch origin
          echo "********Step 3*******"
          git status
          echo "********Step 4*******"
          git checkout test_workflow
          echo "********Step 5*******"
          git status
          echo "********Step 6*******"
          git rebase master
          echo "********Step 7*******"
