name: Testing
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout test_workflow
          git rebase master
          echo "remote ${{ git remote -v }}"
